# xrlib

name: android-latest

on:
  push:
    branches: ['**']  
  pull_request:
    branches: ['main']


jobs:
    build-shared:
        uses: ./.github/workflows/_src_android_builds.yml
        with:
          matrix-json: >
            {
              "build_type": ["debug", "release"],
              "enable_xrvk": ["ON", "OFF"]
            }
          build-as-static : "OFF"
          export-artifacts: "OFF"
