# xrlib

name: desktop-releases

on:
  push:
    tags:
      - 'v*.*.*.*'   

jobs:
    build-shared:
        uses: ./.github/workflows/_src_desktop_builds.yml
        with:
          matrix-json: >
            {
                "os": ["ubuntu-latest", "windows-latest"],
                "build_type": ["release"],
                "cpp_compiler": ["g++", "clang++", "cl"],
                "enable_xrvk": ["ON", "OFF"],
                "include": [
                        {
                            "os": "windows-latest",
                            "cpp_compiler": "cl"
                        },
                        {
                            "os": "ubuntu-latest",
                            "cpp_compiler": "g++"
                        },
                        {
                            "os": "ubuntu-latest",
                            "cpp_compiler": "clang++"
                        }
                    ],
                 "exclude": [
                        {
                            "os": "windows-latest",
                            "cpp_compiler": "g++"
                        },
                        {
                            "os": "windows-latest",
                            "cpp_compiler": "clang++"
                        },
                        {
                            "os": "ubuntu-latest",
                            "cpp_compiler": "cl"
                        }
                    ]
            }
          build-as-static : "OFF"
          export-artifacts: "ON"

    build-static:
        uses: ./.github/workflows/_src_desktop_builds.yml
        with:
          matrix-json: >
            {
                "os": ["ubuntu-latest", "windows-latest"],
                "build_type": ["release"],
                "cpp_compiler": ["g++", "clang++", "cl"],
                "enable_xrvk": ["ON", "OFF"],
                "include": [
                        {
                            "os": "windows-latest",
                            "cpp_compiler": "cl"
                        },
                        {
                            "os": "ubuntu-latest",
                            "cpp_compiler": "g++"
                        },
                        {
                            "os": "ubuntu-latest",
                            "cpp_compiler": "clang++"
                        }
                    ],
                 "exclude": [
                        {
                            "os": "windows-latest",
                            "cpp_compiler": "g++"
                        },
                        {
                            "os": "windows-latest",
                            "cpp_compiler": "clang++"
                        },
                        {
                            "os": "ubuntu-latest",
                            "cpp_compiler": "cl"
                        }
                    ]
            }
          build-as-static : "ON"
          export-artifacts: "ON"

    package-includes:
        runs-on: ubuntu-latest
        needs: [build-shared, build-static]
        steps:
            - run: |
                mkdir ${{ github.ref_name }}_xrlib_source
                mkdir ${{ github.ref_name }}_xrlib_include
         
            - uses: actions/download-artifact@v4
              with:
                name: xrlib-source
                path: ${{ github.ref_name }}_xrlib_source

            - run: |
                rm -f ./${{ github.ref_name }}_xrlib_source/include/project_config.h
                cp -r ./${{ github.ref_name }}_xrlib_source/include ./${{ github.ref_name }}_xrlib_include
                cp ./${{ github.ref_name }}_xrlib_source/LICENSE ./${{ github.ref_name }}_xrlib_include/include
                cp -r ./${{ github.ref_name }}_xrlib_source/third_party/openxr/include/openxr ./${{ github.ref_name }}_xrlib_include
                cp ./${{ github.ref_name }}_xrlib_source/third_party/openxr/LICENSE ./${{ github.ref_name }}_xrlib_include/openxr

            - uses: actions/upload-artifact@v4
              with:
                name: xrlib-${{ github.ref_name }}-INCLUDE
                path: ./${{ github.ref_name }}_xrlib_include

            - uses: geekyeggo/delete-artifact@v5
              with:
                name: xrlib-source
                failOnError: false

    package-windows:
        runs-on: windows-latest
        needs: [build-shared, build-static]
        steps:
            - run: |
                mkdir ${{ github.ref_name }}_xrlib_binaries_windows-shared
                mkdir ${{ github.ref_name }}_xrlib_binaries_windows-shared/with_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_windows-shared/no_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_windows-static
                mkdir ${{ github.ref_name }}_xrlib_binaries_windows-static/with_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_windows-static/no_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-windows-latest_compiler_cl_static_OFF-xrvk_ON
                path: ${{ github.ref_name }}_xrlib_binaries_windows-shared/with_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-windows-latest_compiler_cl_static_OFF-xrvk_OFF
                path: ${{ github.ref_name }}_xrlib_binaries_windows-shared/no_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-windows-latest_compiler_cl_static_ON-xrvk_ON
                path: ${{ github.ref_name }}_xrlib_binaries_windows-static/with_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-windows-latest_compiler_cl_static_ON-xrvk_OFF
                path: ${{ github.ref_name }}_xrlib_binaries_windows-static/no_renderer
              
            - uses: actions/upload-artifact@v4
              with:
                name: xrlib_${{ github.ref_name }}-windows-shared-libs
                path: ./${{ github.ref_name }}_xrlib_binaries_windows-shared

            - uses: actions/upload-artifact@v4
              with:
                name: xrlib_${{ github.ref_name }}-windows-static-libs
                path: ./${{ github.ref_name }}_xrlib_binaries_windows-static

            - uses: geekyeggo/delete-artifact@v5
              with:
                name: xrlib-windows-latest_*
                failOnError: false

    package-linux:
        runs-on: ubuntu-latest
        needs: [build-shared, build-static]
        steps:
            - run: |
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/gnu
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/gnu/with_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/gnu/no_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/clang
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/clang/with_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/clang/no_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-static
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/gnu
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/gnu/with_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/gnu/no_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/clang
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/clang/with_renderer
                mkdir ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/clang/no_renderer

            # Assemble all shared libraries
            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_g++_static_OFF-xrvk_ON
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/gnu/with_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_g++_static_OFF-xrvk_OFF
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/gnu/no_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_clang++_static_OFF-xrvk_ON
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/clang/with_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_clang++_static_OFF-xrvk_OFF
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-shared/clang/no_renderer
            
            # Assemble all static libraries
            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_g++_static_ON-xrvk_ON
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/gnu/with_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_g++_static_ON-xrvk_OFF
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/gnu/no_renderer
              
            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_clang++_static_ON-xrvk_ON
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/clang/with_renderer

            - uses: actions/download-artifact@v4
              with:
                name: xrlib-ubuntu-latest_compiler_clang++_static_ON-xrvk_OFF
                path: ${{ github.ref_name }}_xrlib_binaries_ubuntu-static/clang/no_renderer

            # Upload finalized library compilations
            - uses: actions/upload-artifact@v4
              with:
                name: xrlib_${{ github.ref_name }}-ubuntu-shared-libs
                path: ./${{ github.ref_name }}_xrlib_binaries_ubuntu-shared

            - uses: actions/upload-artifact@v4
              with:
                name: xrlib_${{ github.ref_name }}-ubuntu-static-libs
                path: ./${{ github.ref_name }}_xrlib_binaries_ubuntu-static

            - uses: geekyeggo/delete-artifact@v5
              with:
                name: xrlib-ubuntu-latest_*
                failOnError: false
