# xrlib

name: ubuntu-latest

on:
  push:
    branches: ['**']   
  pull_request:
    branches: ['main']    


jobs:
    build:
        uses: ./.github/workflows/_src_desktop_builds.yml
        with:
          matrix-json: >
            {
              "os": ["ubuntu-latest"],
              "build_type": ["debug", "release"],
              "enable_xrvk": ["ON", "OFF"],
              "cpp_compiler": ["g++", "clang++"]
            }
          build-as-static : "OFF"
          export-artifacts: "OFF"
